services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    stdin_open: true
    tty: true
    ports:
      - "5000:3000"
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle
volumes:
  gem_cache:
