# Name of your application. Used to uniquely configure containers.
service: festivalplanner

# Name of the container image.
image: skeptor/festivalplanner

# Deploy to these servers.
servers:
  web:
    hosts:
      - 51.44.6.98
    labels:
      traefik.http.routers.preparatufesti.rule: Host(`preparatufesti.es`) && PathPrefix(`/`)
      traefik.http.routers.preparatufesti.entrypoints: websecure
      traefik.http.routers.preparatufesti.tls: true
      traefik.http.routers.preparatufesti.tls.certresolver: letsencrypt
      traefik.http.services.preparatufesti.loadbalancer.server.port: 3000

accessories:
  db:
    image: alpine:latest  # Lightweight container for volume mounting
    files:
      - data:/data
    commands:
      init: mkdir -p /data


# Credentials for your image host.
registry:
  username: skeptor
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    DB_FILENAME: /data/production.sqlite3
    RAILS_SERVE_STATIC_FILES: "true"
  secret:
    - RAILS_MASTER_KEY


# Use a different ssh user than root
#
ssh:
  user: ubuntu
  keys: [ "~/.ssh/festivalPlanner-prod.pem" ]

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "pablo.navarro@preparatufesti.es"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint: "web"
