# Name of your application. Used to uniquely configure containers.
service: festivalplanner

# Name of the container image.
image: skeptor/festivalplanner

# Deploy to these servers.
servers:
  web:
    hosts:
      - 51.44.6.98
    labels:
      traefik.http.routers.preparatufesti.rule: Host(`preparatufesti.es`) && PathPrefix(`/`)
      traefik.http.routers.preparatufesti.entrypoints: websecure
      traefik.http.routers.preparatufesti.tls: true
      traefik.http.routers.preparatufesti.tls.certresolver: letsencrypt
      traefik.http.services.preparatufesti.loadbalancer.server.port: 3000

accessories:
  db:
    host: 51.44.6.98  # Same host as web server
    image: alpine:latest
    volumes:
      - data:/data
    cmd: sh -c "mkdir -p /data && touch /data/production.sqlite3 && chmod 0666 /data/production.sqlite3 && tail -f /dev/null"

# Credentials for your image host.
registry:
  username: skeptor
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  clear:
    DB_FILENAME: /data/production.sqlite3
    RAILS_SERVE_STATIC_FILES: "true"
  secret:
    - RAILS_MASTER_KEY


# Use a different ssh user than root
#
ssh:
  user: ubuntu
  keys: [ "~/.ssh/festivalPlanner-prod.pem" ]
