# Name of your application. Used to uniquely configure containers.
service: festivalplanner

# Name of the container image.
image: skeptor/festivalplanner

# Deploy to these servers.
servers:
  web:
    - preparatufesti.es

proxy:
  ssl: true
  host: preparatufesti.es

volumes:
  - "store_storage:/rails/storage"

# Credentials for your image host.
registry:
  username: skeptor
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY

# Use a different ssh user than root
#
ssh:
  user: ubuntu
  keys: [ "~/.ssh/festivalPlanner-prod.pem" ]

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
