# Name of your application. Used to uniquely configure containers.
service: festivalplanner

# Name of the container image.
image: skeptor/festivalplanner

# Deploy to these servers.
servers:
  web:
    - 51.44.6.98

proxy:
  ssl: true
  host: preparatufesti.es

accessories:
  db:
    host: 51.44.6.98  # Same host as web server
    image: alpine:latest
    volumes:
      - data:/data
    cmd: sh -c "mkdir -p /data && touch /data/production.sqlite3 && chmod 0666 /data/production.sqlite3 && tail -f /dev/null"

# Credentials for your image host.
registry:
  username: skeptor
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    DB_FILENAME: /data/production.sqlite3
    RAILS_SERVE_STATIC_FILES: "true"

# Use a different ssh user than root
#
ssh:
  user: ubuntu
  keys: [ "~/.ssh/festivalPlanner-prod.pem" ]

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
